Repository NowYouKnowProgramming/webdev-learning-materials, pull requests merged in 2023-03, with the labels that each got.

#195 Docs UI update
  src/components/LeftSidebar/LeftSidebar.astro
  src/components/RightSidebar/ThemeToggleButton.css
  src/styles/theme.css
Labels: enhancement

#202 React materials update
  src/pages/technologies/react.md
Labels: documentation, 😷 docs maintenance 😷, 😍 new content for existing docs 😍

#204 Docs/productivity learning update
  src/config.ts
  src/pages/common/learning_to_learn.md
  src/pages/common/productivity.md
  src/pages/software/other_tools.md
Labels: 🎈 new docs page 🎈, 😍 new content for existing docs 😍

#205 Add tech stack icons to README.md
  README.md
Labels: documentation

#207 Feat: add meta images for multiple docs pages
  public/metaimages/css.png
  public/metaimages/git.png
  public/metaimages/html.png
  public/metaimages/javascript.png
  public/metaimages/nextjs.png
  public/metaimages/nodejs.png
  public/metaimages/react.png
  public/metaimages/redux.png
  public/metaimages/testing.png
  public/metaimages/typescript.png
  src/components/HeadSEO.astro
  src/pages/principles/testing.md
  src/pages/technologies/css.md
  src/pages/technologies/git.md
  src/pages/technologies/html.md
  src/pages/technologies/javascript.md
  src/pages/technologies/nextjs.md
  src/pages/technologies/nodejs.md
  src/pages/technologies/react.md
  src/pages/technologies/redux.md
  src/pages/technologies/typescript.md
  src/styles/index.css
Labels: enhancement
